### PR TITLE
Feature/descriptive buttons

### PR DESCRIPTION
**Pull request by nathanb95**
Back buttons will now display title of the previous view

### CODE REVIEW

**Comment by jzukosky** [comment]
I think I'd prefer if we changed this through the storyboard. Less lines of code and if we want a name change, it'll be easier. If you select the View Controller's navigation item on the storyboard, you can set the back button attribute in the Attributes Inspector that way

**Comment by nathanb95** [comment]
Would I be able to do that though since both Schedule and Map views use EventDetailViewController when a view cell is selected?

**Comment by jzukosky** [comment]
Yup. You set the back button attribute on the view controller that creates the segue, not the one that receives it, so it'll still be able to tell which view controller sent the segue and assign that back button title

**Comment by nathanb95** [comment]
Got it. I'll go ahead and make the changes

**Comment by nathanb95** [comment]
Should be all good now!

**Review by jzukosky — APPROVED** [review]

**Pull request merged**
