### PR TITLE
Added Cosmetic UI Star, Favorite and Unfavorite

### PR DESCRIPTION
**Pull request by okrek6**
Let me know what you guys think.

### CODE REVIEW

**Review by jzukosky — APPROVED** [review]

**Comment by okrek6** [comment]
screen shot 2018-08-28 at 3 39 29 pm
screen shot 2018-08-30 at 5 08 35 pm
screen shot 2018-08-30 at 5 08 47 pm
screen shot 2018-08-30 at 5 08 56 pm
screen shot 2018-08-30 at 5 09 01 pm

**Comment by okrek6** [comment]
Ignore the Map image

**Review by eteters — APPROVED** [review]

**Comment by jzukosky** [comment]
@okrek6 Go ahead and merge this and get a brand new little green square on your GitHub 😉

**Comment by jzukosky** [comment]
Oh yeah also don't forget to delete the branch after merging

**Pull request merged**
